///////////////////////////////////////////////////////////////////////////////
// DATA DOWNLOADED FROM: https://ocrdata.ed.gov/estimations/2017-2018
//   
// date downloaded: July 23, 2021
//
// downloaded CRDC 2017-18 "State and National Estimations" Excel spreadsheets
// (1) "Course Enrollment" > "Advanced Placement Courses" > 
//     "2017-18 Advanced Placement Total Enrollment Estimations" >
//     "Advanced placement" https://ocrdata.ed.gov/assets/downloads/2017-2018/Course-Enrollment/Advanced-Placement-(courses)/Advanced-Placement-Enrollment.xlsx
//  --> SEE ATTACHMENT: "[excel] CRDC state estimates_AP Enrollment_2017-2018.xlsx"
//
// (2) "College Preparatory Exams" > "Advanced Placement Exams" > 
//     "2017-18 Advanced Placement Exam Taking Estimations" > "Did not take 
//      AP Exam" https://ocrdata.ed.gov/assets/downloads/2017-2018/College-Prepatory-Exams/Advanced-Placement-Exams/Advanced-Placement-Participation-by-state_Did-Not-Take-Exam.xlsx
//  --> SEE ATTACHMENT: "[excel] CRDC state estimates_AP participation_Did Not Take Exam_2017-2018.xlsx"
// 
// (3) "College Preparatory Exams" > "Advanced Placement Exams" > 
//     "2017-18 Advanced Placement Exam Taking Estimations" > "Took AP Exam" https://ocrdata.ed.gov/assets/downloads/2017-2018/College-Prepatory-Exams/Advanced-Placement-Exams/Advanced-Placement-Participation-by-state_Took-Exam.xlsx
//  --> SEE ATTACHMENT: "[excel] CRDC state estimates_AP participation_Took Exam_2017-2018.xlsx"
///////////////////////////////////////////////////////////////////////////////


// CHANGE JUST THIS LINE
global directory = "C:\Users\lrestrepo\Documents\Github_repos\The-Learning-Curve\2022_03_17-AP_Enrollment"

cd "${directory}"

global data = "${directory}\data"
global urbinst = "${data}\Urban Institute_AP"

cap n mkdir "${data}"
cap n mkdir "${urbinst}"

graph set window fontface "lato"

* IMPORT DATA SET & CHECK FOR MISSING DATA: AP ENROLLMENT - TOTAL
** import AP ENROLLMENT - TOTAL

*** REVIEWER TO UPDATE FILE LOCATION AS NEEDED 
import excel "https://ocrdata.ed.gov/assets/downloads/2017-2018/Course-Enrollment/Advanced-Placement-(courses)/Advanced-Placement-Enrollment.xlsx", sheet("Total") clear
describe        // all variables imported as strings

drop if A == "" // drop notes and variable labels 
	
rename A APENR_sample_definition
rename B state_name
rename C APENR_num_total_students
rename D APENR_num_AIAN
rename E APENR_perc_AIAN
rename F APENR_num_ASIAN
rename G APENR_perc_ASIAN
rename H APENR_num_HISP
rename I APENR_perc_HISP
rename J APENR_num_BLACK
rename K APENR_perc_BLACK
rename L APENR_num_WHITE
rename M APENR_perc_WHITE
rename N APENR_num_HAWOPI
rename O APENR_perc_HAWOPI
rename P APENR_num_MULTIRACE
rename Q APENR_perc_MULTIRACE
rename R APENR_num_SWDIDEA
rename S APENR_perc_SWDIDEA
rename T APENR_num_EL
rename U APENR_perc_EL
rename V APENR_num_schools
rename W APENR_perc_school_report

sort state_name

** check for missing data in AP ENROLLMENT - TOTAL
foreach var in APENR_num_total_students APENR_num_AIAN APENR_perc_AIAN APENR_num_ASIAN APENR_perc_ASIAN APENR_num_HISP APENR_perc_HISP APENR_num_BLACK APENR_perc_BLACK APENR_num_WHITE APENR_perc_WHITE APENR_num_HAWOPI APENR_perc_HAWOPI APENR_num_MULTIRACE APENR_perc_MULTIRACE APENR_num_SWDIDEA APENR_perc_SWDIDEA APENR_num_EL APENR_perc_EL APENR_num_schools APENR_perc_school_report {
	replace `var' ="." if `var'=="#" // NOTE: According to CRDC spreadsheet 
									     // "# rounds to zero"
	replace `var' ="." if `var'=="S" //NOTE: Likely typo; addressed below 
	destring `var', replace
}
describe     
misstable summarize  // 1 missing observation for APENR_perc_BLACK
					 // 4 missing observations for APENR_perc_HAWOPI 
								   
// NB: Missing observations can be manually generated by dividing number of
//     subgroup (i.e., APENR_perc_BLACK and APENR_perc_HAWOPI) with  
//     APENR_num_total_students.
// --> SEE ATTACHMENT: "[excel] CRDC state estimates_AP Enrollment_2017-2018 with missing data highlighted and manually generated.xlsx"
		
** update variables to address missing data in AP ENROLLMENT - TOTAL
generate APENR_percnew_BLACK = (APENR_num_BLACK / APENR_num_total_students) * 100
drop APENR_perc_BLACK
		
generate APENR_percnew_HAWOPI = (APENR_num_HAWOPI / APENR_num_total_students) * 100
drop APENR_perc_HAWOPI
misstable summarize 
			
tempfile apenr_total
save "${data}\apenr_total.dta", replace 



* IMPORT DATA SET & CHECK FOR MISSING DATA: AP TEST NON-PARTICIPATION - TOTAL
** import AP TEST NON-PARTICIPATION - TOTAL

*** REVIEWER TO UPDATE FILE LOCATION AS NEEDED 
import excel "https://ocrdata.ed.gov/assets/downloads/2017-2018/College-Prepatory-Exams/Advanced-Placement-Exams/Advanced-Placement-Participation-by-state_Did-Not-Take-Exam.xlsx", sheet("Total") clear
	describe        // all variables imported as strings
	browse

	drop if A == "" // drop notes and variable labels 
	
	rename A APNO_sample_definition
	rename B state_name
	rename C APNO_num_total_students
	rename D APNO_num_AIAN
	rename E APNO_perc_AIAN
	rename F APNO_num_ASIAN
	rename G APNO_perc_ASIAN
	rename H APNO_num_HISP
	rename I APNO_perc_HISP
	rename J APNO_num_BLACK
	rename K APNO_perc_BLACK
	rename L APNO_num_WHITE
	rename M APNO_perc_WHITE
	rename N APNO_num_HAWOPI
	rename O APNO_perc_HAWOPI
	rename P APNO_num_MULTIRACE
	rename Q APNO_perc_MULTIRACE
	rename R APNO_num_SWDIDEA
	rename S APNO_perc_SWDIDEA
	rename T APNO_num_EL
	rename U APNO_perc_EL
	rename V APNO_num_schools
	rename W APNO_perc_school_report

	sort state_name

** check for missing data in AP ENROLLMENT - TOTAL
	foreach var in APNO_num_total_students APNO_num_AIAN APNO_perc_AIAN APNO_num_ASIAN APNO_perc_ASIAN APNO_num_HISP APNO_perc_HISP APNO_num_BLACK APNO_perc_BLACK APNO_num_WHITE APNO_perc_WHITE APNO_num_HAWOPI APNO_perc_HAWOPI APNO_num_MULTIRACE APNO_perc_MULTIRACE APNO_num_SWDIDEA APNO_perc_SWDIDEA APNO_num_EL APNO_perc_EL APNO_num_schools APNO_perc_school_report {
		replace `var' ="." if `var'=="#" // NOTE: According to CRDC spreadsheet 
									     // "# rounds to zero"
		replace `var' ="." if `var'=="S" //NOTE: Likely typo; addressed below 
									
		destring `var', replace float
	}
	describe     
	misstable summarize  // 1 missing observation for APENR_perc_BLACK
						 // 3 missing observations for APENR_perc_HAWOPI
						 // 1 missing observations for APENR_perc_AIAN
								   
// NB: Missing observations can be manually generated by dividing number of
//     subgroup (i.e., APENR_perc_BLACK and APENR_perc_HAWOPI) with  
//     APENR_num_total_students.
// --> SEE ATTACHMENT: "[excel] CRDC state estimates_AP Enrollment_2017-2018 with missing data highlighted and manually generated.xlsx"
	replace APNO_perc_BLACK = APNO_num_BLACK/APNO_num_total_students*100 if APNO_perc_BLACK==.
	replace APNO_perc_HAWOPI = APNO_num_HAWOPI/APNO_num_total_students*100 if APNO_perc_HAWOPI==.
	replace APNO_perc_AIAN = APNO_num_AIAN/APNO_num_total_students*100 if APNO_perc_AIAN==.
** create new variable to confirm that all perc_race variables sum to 100% (for GRAPH #4)		
	generate APNO_perc_total_students = APNO_perc_AIAN + APNO_perc_ASIAN + APNO_perc_HISP + APNO_perc_WHITE + APNO_perc_MULTIRACE + APNO_perc_BLACK + APNO_perc_HAWOPI
		
	browse state_name APNO_perc_AIAN APNO_perc_ASIAN APNO_perc_HISP APNO_perc_WHITE APNO_perc_MULTIRACE APNO_perc_BLACK APNO_perc_HAWOPI APNO_perc_total_students

** create new variable that collapses perc_AIAN, perc_MULTIRACE, perc_HAWOPI into 1 variable (for GRAPH #4)		
	generate APNO_perc_OTHER = APNO_perc_AIAN + APNO_perc_MULTIRACE + APNO_perc_HAWOPI

tempfile apnotest_total
save "${data}\apnotest_total.dta", replace 



* IMPORT DATA SET & CHECK FOR MISSING DATA: AP TEST PARTICIPATION - TOTAL
** import AP TEST PARTICIPATION - TOTAL

*** REVIEWER TO UPDATE FILE LOCATION AS NEEDED 
import excel "https://ocrdata.ed.gov/assets/downloads/2017-2018/College-Prepatory-Exams/Advanced-Placement-Exams/Advanced-Placement-Participation-by-state_Took-Exam.xlsx", sheet("Total") clear
describe        // all variables imported as strings


drop if A == ""  // drop notes and variable labels 

rename A APYES_sample_definition
rename B state_name
rename C APYES_num_total_students
rename D APYES_num_AIAN
rename E APYES_perc_AIAN
rename F APYES_num_ASIAN
rename G APYES_perc_ASIAN
rename H APYES_num_HISP
rename I APYES_perc_HISP
rename J APYES_num_BLACK
rename K APYES_perc_BLACK
rename L APYES_num_WHITE
rename M APYES_perc_WHITE
rename N APYES_num_HAWOPI
rename O APYES_perc_HAWOPI
rename P APYES_num_MULTIRACE
rename Q APYES_perc_MULTIRACE
rename R APYES_num_SWDIDEA
rename S APYES_perc_SWDIDEA
rename T APYES_num_EL
rename U APYES_perc_EL
rename V APYES_num_schools
rename W APYES_perc_school_report

sort state_name

** check for missing data in AP TEST PARTICIPATION - TOTAL
foreach var in APYES_num_total_students APYES_num_AIAN APYES_perc_AIAN APYES_num_ASIAN APYES_perc_ASIAN APYES_num_HISP APYES_perc_HISP APYES_num_BLACK APYES_perc_BLACK APYES_num_WHITE APYES_perc_WHITE APYES_num_HAWOPI APYES_perc_HAWOPI APYES_num_MULTIRACE APYES_perc_MULTIRACE APYES_num_SWDIDEA APYES_perc_SWDIDEA APYES_num_EL APYES_perc_EL APYES_num_schools APYES_perc_school_report {
	replace `var' ="." if `var'=="#" // NOTE: According to CRDC spreadsheet
		                                 // "# rounds to zero"
	destring `var', replace
	}

describe
misstable summarize  // 1 missing observation for APYES_perc_BLACK
					 // 2 missing observation for APYES_perc_HAWOPI

// NB: Missing observations can be manually generated by dividing number of 
//     subgroup (i.e., APYES_perc_BLACK, APYES_perc_HAWOPI) with
//     APYES_num_total_students
// --> SEE ATTACHMENT: "[excel] CRDC state estimates_AP participation_Took Exam_2017-2018 with missing data highlighted"

** update variables to address missing data in AP TEST PARTICIPATION - TOTAL
generate APYES_percnew_BLACK = (APYES_num_BLACK / APYES_num_total_students) * 100
drop APYES_perc_BLACK
		
generate APYES_percnew_HAWOPI = (APYES_num_HAWOPI / APYES_num_total_students) * 100
drop APYES_perc_HAWOPI
misstable summarize 

tempfile apyestest_total
save "${data}\apyestest_total.dta", replace 

	

* MERGE TO CREATE ANALYTIC DATA SET: AP ENROLLMENT_all + AP TEST PARTICIPATION_all + AP TEST NON-PARTICIPATION_all
use "${data}\apenr_total.dta", clear
merge 1:1 state_name using "${data}\apyestest_total.dta"   // all merged successfully
tab _merge
drop _merge
merge 1:1 state_name using "${data}\apnotest_total.dta"   // all merged successfully
drop _merge

describe

save "${urbinst}\ap_analytic_file.dta", replace


///////////////////////////////////////////////////////////////////////////////

* BASIC DESCRIPTIVE STATISTICS for ALL STUDENTS, EL, SWD IDEA

** proportion of students who took at least 1 exam (from APYES dataset) / students enrolled in at least 1 course (from APENR dataset) - ALL STUDENTS
*** READ AS: "##% of ALL students in STATE_NAME who were enrolled in at least one AP class during the 2017-2018 school year went on to take at least one AP exam for their enrolled AP classes"
generate propYES_ENR_total = APYES_num_total_students/APENR_num_total_students

** proportion gap between course enrollment and taking at least 1 exam - ALL STUDENTS
generate gapYES_ENR_total = 1-propYES_ENR_total
display 1-(APYES_num_total_students/APENR_num_total_students)


** proportion of students who took at least 1 exam (from APYES dataset) / students enrolled in at least 1 course (from APENR dataset) - ENGLISH LEARNERS
*** READ AS: "##% of EL in STATE_NAME who were enrolled in at least one AP class during the 2017-2018 school year went on to take at least one AP exam for their enrolled AP classes"
generate propYES_ENR_EL = APYES_num_EL/APENR_num_EL

** proportion gap between course enrollment and taking at least 1 exam - EL
generate gapYES_ENR_EL = 1-propYES_ENR_EL
display 1-(APYES_num_EL/APENR_num_EL)


** proportion of students who took at least 1 exam (from APYES dataset) / students enrolled in at least 1 course (from APENR dataset) - SWD IDEA
*** READ AS: "##% of SWDIDEA in STATE_NAME who were enrolled in at least one AP class during the 2017-2018 school year went on to take at least one AP exam for their enrolled AP classes"
generate propYES_ENR_SWDIDEA = APYES_num_SWDIDEA/APENR_num_SWDIDEA

** proportion gap between course enrollment and taking at least 1 exam - SWDIDEA
generate gapYES_ENR_SWDIDEA = 1-propYES_ENR_SWDIDEA
display 1-(APYES_num_SWDIDEA/APENR_num_SWDIDEA)

///////////////////////////////////////////////////////////////////////////////

* BASIC DESCRIPTIVE STATISTICS by RACE

** proportion of students who took at least 1 exam (from APYES dataset) / students enrolled in at least 1 course (from APENR dataset) - BLACK
*** READ AS: "##% of BLACK in STATE_NAME who were enrolled in at least one AP class during the 2017-2018 school year went on to take at least one AP exam for their enrolled AP classes"
generate propYES_ENR_BLACK = APYES_num_BLACK/APENR_num_BLACK

** proportion gap between course enrollment and taking at least 1 exam - BLACK
generate gapYES_ENR_BLACK = 1-propYES_ENR_BLACK
display 1-(APYES_num_BLACK/APENR_num_BLACK)


** proportion of students who took at least 1 exam (from APYES dataset) / students enrolled in at least 1 course (from APENR dataset) - WHITE
*** READ AS: "##% of WHITE in STATE_NAME who were enrolled in at least one AP class during the 2017-2018 school year went on to take at least one AP exam for their enrolled AP classes"
generate propYES_ENR_WHITE = APYES_num_WHITE/APENR_num_WHITE

** proportion gap between course enrollment and taking at least 1 exam - WHITE
generate gapYES_ENR_WHITE = 1-propYES_ENR_WHITE
display 1-(APYES_num_WHITE/APENR_num_WHITE)


** proportion of students who took at least 1 exam (from APYES dataset) / students enrolled in at least 1 course (from APENR dataset) - HISPANIC
*** READ AS: "##% of HISP in STATE_NAME who were enrolled in at least one AP class during the 2017-2018 school year went on to take at least one AP exam for their enrolled AP classes"
generate propYES_ENR_HISP = APYES_num_HISP/APENR_num_HISP

** proportion gap between course enrollment and taking at least 1 exam - HISPANIC
generate gapYES_ENR_HISP = 1-propYES_ENR_HISP
display 1-(APYES_num_HISP/APENR_num_HISP)


** proportion of students who took at least 1 exam (from APYES dataset) / students enrolled in at least 1 course (from APENR dataset) - AMERICAN INDIAN / ALASKAN NATIVE
*** READ AS: "##% of AIAN in STATE_NAME who were enrolled in at least one AP class during the 2017-2018 school year went on to take at least one AP exam for their enrolled AP classes"
generate propYES_ENR_AIAN = APYES_num_AIAN/APENR_num_AIAN

** proportion gap between course enrollment and taking at least 1 exam - AMERICAN INDIAN / ALASKAN NATIVE
generate gapYES_ENR_AIAN = 1-propYES_ENR_AIAN
display 1-(APYES_num_AIAN/APENR_num_AIAN)


** proportion of students who took at least 1 exam (from APYES dataset) / students enrolled in at least 1 course (from APENR dataset) - ASIAN
*** READ AS: "##% of ASIAN in STATE_NAME who were enrolled in at least one AP class during the 2017-2018 school year went on to take at least one AP exam for their enrolled AP classes"
generate propYES_ENR_ASIAN = APYES_num_ASIAN/APENR_num_ASIAN

** proportion gap between course enrollment and taking at least 1 exam - ASIAN
generate gapYES_ENR_ASIAN = 1-propYES_ENR_ASIAN
display 1-(APYES_num_ASIAN/APENR_num_ASIAN)


** proportion of students who took at least 1 exam (from APYES dataset) / students enrolled in at least 1 course (from APENR dataset) - HAWAIIAN / PACIFIC ISLANDER
*** READ AS: "##% of HAWOPI in STATE_NAME who were enrolled in at least one AP class during the 2017-2018 school year went on to take at least one AP exam for their enrolled AP classes"
generate propYES_ENR_HAWOPI = APYES_num_HAWOPI/APENR_num_HAWOPI

** proportion gap between course enrollment and taking at least 1 exam - HAWAIIAN / PACIFIC ISLANDER
generate gapYES_ENR_HAWOPI = 1-propYES_ENR_HAWOPI
display 1-(APYES_num_HAWOPI/APENR_num_HAWOPI)


** proportion of students who took at least 1 exam (from APYES dataset) / students enrolled in at least 1 course (from APENR dataset) - MULTIRACE
*** READ AS: "##% of MULTIRACE in STATE_NAME who were enrolled in at least one AP class during the 2017-2018 school year went on to take at least one AP exam for their enrolled AP classes"
generate propYES_ENR_MULTIRACE = APYES_num_MULTIRACE/APENR_num_MULTIRACE

** proportion gap between course enrollment and taking at least 1 exam - MULTIRACE
generate gapYES_ENR_MULTIRACE = 1-propYES_ENR_MULTIRACE
display 1-(APYES_num_MULTIRACE/APENR_num_MULTIRACE)

////////////////////////////////////////////////////////////////////////////

* CREATE GRAPH #1: Percentage of ALL, EL, SWDIDEA students in United States who were enrolled in at least one AP class also took one or more AP exams for one or more AP courses enrolled"
	
preserve
keep if state_name=="50 states, District of Columbia, and Puerto Rico"
keep propYES_ENR_total propYES_ENR_EL propYES_ENR_SWDIDEA APENR_num_total_students APENR_num_EL APENR_num_SWDIDEA
rename APENR_num_total_students APENR_num_total 
gen i = 1
reshape long propYES_ENR_, i(i) j(cat) str
tab cat
gen y = propYES_ENR_
		
replace y = y*100
		
gen x = 1 if cat=="total" 
replace x = 2 if cat=="EL"
replace x = 3 if cat=="SWDIDEA"
gen y_lab = round(y,.1)
tostring y_lab, replace force
gen y_label = substr(y_lab, 1, 4)
replace y_label = y_label + "%"
		
gen n_label = "".""
foreach cat in total EL SWDIDEA {
sum APENR_num_`cat'
local n_`cat' = r(mean)
di `n_`cat''
replace n_label = "`n_`cat''" if cat=="`cat'"
}
					
gen n_lab_dig_count = n_label
tab   n_lab_dig_count
replace n_label = "n=" + substr(n_label,-7,1) + "," + substr(n_label,-6,3) + ","  + 	substr(n_label,-3,3) if strlen(n_lab_dig_count)==7
replace n_label = "n=" + substr(n_label,-6,3) + ","  + substr(n_label,-3,3) if strlen(n_lab_dig_count)==6
replace n_label = "n=" + substr(n_label,-5,2) + ","  + substr(n_label,-3,3) if strlen(n_lab_dig_count)==5
replace n_label = "n=" + substr(n_label,-4,1) + ","  + substr(n_label,-3,3) if strlen(n_lab_dig_count)==4
replace n_label = "n=" + substr(n_label,-3,3) if strlen(n_lab_dig_count)==3
replace n_label = "n=" + substr(n_label,-2,2) if strlen(n_lab_dig_count)==2
replace n_label = "n=" + substr(n_label,-1,1) if strlen(n_lab_dig_count)==1
		
gen n_label_x = -10
tab n_label
gen x_label = "All Students" if cat=="total"
replace x_label = "English Learners" if cat=="EL"
replace x_label = "Students" if cat=="SWDIDEA"
gen x_label2 = "with disabilities" if cat=="SWDIDEA"
gen x_label_y = 0
gen x_label_y2 = -5
		
twoway bar y x if cat=="total", bcolor("22 150 210") barwidth(.75) ///
	|| bar y x if cat=="EL", bcolor("22 150 210") barwidth(.75) ///
	|| bar y x if cat=="SWDIDEA", bcolor("22 150 210") barwidth(.75) ///
	|| scatter y x, msize(zero) mlabel(y_label) mlabpos(12) mlabcolor(black) ///
	|| scatter x_label_y x, msize(zero) mlabel(x_label) mlabpos(6) mlabcolor(black) ///
	|| scatter x_label_y2 x, msize(zero) mlabel(x_label2) mlabpos(6) mlabcolor(black) ///
	|| scatter n_label_x x, msize(zero) mlabel(n_label) mlabpos(6) mlabcolor(black) ///
	|| pcarrowi 0 .5 100 .5, lcolor(red) msize(zero) lcolor(black) lwidth(.2) ///
	ylabel(0(20)100, noticks) yline(0, lcolor(black) lwidth(.2)) ///
	xline(0,lcolor(white)) ///
	xlabel(1 "All students" ///
	2 "English Learners" ///
	3 "Students with disabilities" ///
	, noticks ) ///
	legend(off) /// 
	xtitle("")  xscale(off) ///
	yscale(off) ///
	ylabel(, nogrid) ///
	title("Share of students enrolled in AP courses who took at least one AP exam", position(11) justification(left) color("0 0 0") size(4)) ///
	graphregion(color(white)) bgcolor(white)
		
		tab y
		graph export "${urbinst}\Graph 1_All, EL, SWD.pdf", as(pdf) replace
		
	restore

////////////////////////////////////////////////////////////////////////////	

* CREATE GRAPH #2: Percentage of ALL / RACE students in United States who were enrolled in at least one AP class also took one or more AP exams for one or more AP courses enrolled"	
	
	preserve
		keep if state_name=="50 states, District of Columbia, and Puerto Rico"
		
		keep propYES_ENR* ///
		APENR_num_AIAN ///
		APENR_num_ASIAN ///
		APENR_num_BLACK ///
		APENR_num_WHITE ///
		APENR_num_HISP ///
		APENR_num_HAWOPI ///
		APENR_num_MULTIRACE ///
		APENR_num_total_students
		rename 	APENR_num_total_students 	APENR_num_total
		
		gen i = 1
		reshape long propYES_ENR_ APENR_num_, i(i) j(cat) str
		tab cat
		drop if cat=="EL" | cat=="SWDIDEA"
		tab cat
		gsort -propYES_ENR_
		egen rank = seq()
		replace rank = 0 if cat=="total"
		sort rank
		egen x = seq()
		tab x
		replace x = x*5

		gen y = propYES_ENR_
		replace y = y*100
		
		gen y_lab = round(y,.1)
		tostring y_lab, replace force
		gen y_label = substr(y_lab, 1, 4)
		replace y_label = y_label + "%"
		
		gen n_label = "".""
		foreach cat in AIAN ASIAN BLACK WHITE HISP HAWOPI MULTIRACE total {
		sum APENR_num_ if cat=="`cat'"
		local n_`cat' = r(mean)
		replace n_label = "`n_`cat''" if cat=="`cat'"
		}
		
		gen n_lab_dig_count = n_label
		replace n_label = "n=" + substr(n_label,-7,1) + "," + substr(n_label,-6,3) + ","  + 	substr(n_label,-3,3) if strlen(n_lab_dig_count)==7
		replace n_label = "n=" + substr(n_label,-6,3) + ","  + substr(n_label,-3,3) if strlen(n_lab_dig_count)==6
		replace n_label = "n=" + substr(n_label,-5,2) + ","  + substr(n_label,-3,3) if strlen(n_lab_dig_count)==5
		replace n_label = "n=" + substr(n_label,-4,1) + ","  + substr(n_label,-3,3) if strlen(n_lab_dig_count)==4
		replace n_label = "n=" + substr(n_label,-3,3) if strlen(n_lab_dig_count)==3
		replace n_label = "n=" + substr(n_label,-2,2) if strlen(n_lab_dig_count)==2
		replace n_label = "n=" + substr(n_label,-1,1) if strlen(n_lab_dig_count)==1
		
		gen n_label_x = -10
		tab n_label
		gen x_label = "All Students" if cat=="total"
		replace x_label = "AIAN" if cat=="AIAN"
		replace x_label = "Asian" if cat=="ASIAN"
		replace x_label = "Black" if cat=="BLACK"
		replace x_label = "NHPI" if cat=="HAWOPI"
		replace x_label = "Hispanic" if cat=="HISP"
		replace x_label = "2+ Races" if cat=="MULTIRACE"
		replace x_label = "White" if cat=="WHITE"
		gen x_label_y = 0
		gen x_label_y2 = -5
		
		twoway bar y x if x==5, bcolor("22 150 210") barwidth(3.5)  ysc(r(0 100)) ///
		|| bar y x if x==10, bcolor("22 150 210") barwidth(3.5)  ysc(r(0 100)) ///
		|| bar y x if x==15, bcolor("22 150 210") barwidth(3.5)  ysc(r(0 100)) ///
		|| bar y x if x==20, bcolor("22 150 210") barwidth(3.5)  ysc(r(0 100)) ///
		|| bar y x if x==25, bcolor("22 150 210") barwidth(3.5)  ysc(r(0 100)) ///
		|| bar y x if x==30, bcolor("22 150 210") barwidth(3.5)  ysc(r(0 100)) ///
		|| bar y x if x==35, bcolor("22 150 210") barwidth(3.5)  ysc(r(0 100)) ///
		|| bar y x if x==40, bcolor("22 150 210") barwidth(3.5)  ysc(r(0 100)) ///
		|| scatter y x, msize(zero) mlabel(y_label) mlabpos(12) mlabcolor(black)  ysc(r(0 100)) ///
		|| pcarrowi 0 2.5 100 2.5, lcolor("219 43 39") msize(zero) lcolor("0 0 0") lwidth(.2) ///
		yscale(off) ///
		ylabel(, nogrid) ///
		ylabel(0(20)100, noticks) ///
		xlabel(	5 `" "All Students" "N=`n_total'" "' ///
				10 `" "Asian" "N=`n_ASIAN'" "' /// 
				15 `" "White" "N=`n_WHITE'" "'  /// 
				20 `" "Two or more" "races" "N=`n_MULTIRACE'" "'  ///
				25 `" "Hispanic" "N=`n_HISP'" "'  /// 
				30 `" "Black" "N=`n_BLACK'" "'  ///
				35 `" "NHPI" "N=`n_HAWOPI'" "'  ///
				40 `" "AIAN" "N=`n_AIAN'" "', noticks  labsize(small)) ///
		legend(off) /// 
		ytitle("" " ", size(small)) ///
		xtitle(" ") ///
		title("Share of students enrolled in AP courses" "who took at least one AP exam, by Race or Ethnicity" "", position(11) justification(left) color("0 0 0") size(4)) ///
		note(" " "Source: CRDC 2017-2018" "Note: 'n' reflects the number of public school students enrolled in at least one AP course"  "in all 50 states, the District of Columbia, and Puerto Rico during the 2017-2018 school year.")	///
		graphregion(color(white)) bgcolor(white)
		
		tab cat x // for figuring out the labels
		
		tab y
		graph export "${urbinst}\Graph 2_Race.pdf", as(pdf) replace
		
	restore
		
////////////////////////////////////////////////////////////////////////////
	
* CREATE GRAPH #3: RELATIVE TEST-TAKING ACROSS GROUPS AT STATE-LEVEL: 	

	preserve
		sort state_name
		encode state_name, gen(state_code)

		tab state_code
		tab state_code, nol

		foreach cat in BLACK WHITE ASIAN HISP {
			replace propYES_ENR_`cat'= propYES_ENR_`cat'*100
		}

		** vertical lines
		twoway scatter  propYES_ENR_BLACK	state_code, mcolor("22 150 210") ///
			|| scatter  propYES_ENR_WHITE	state_code, mcolor("85 183 72") ///
			|| scatter  propYES_ENR_ASIAN	state_code, mcolor("92 88 89") ///
			|| scatter  propYES_ENR_HISP	state_code, mcolor("253 191 17") ///
			xlabel( 1 `" "  " "US" "' ///
					2 `" "AL" "' ///
					3 `" "  " "AK" "' ///
					4 `" "AZ" "' ///
					5 `" "  " "AR" "' ///
					6 `" "CA" "' ///
					7 `" "  " "CO" "' ///
					8 `" "CT" "' ///
					9 `" "  " "DE" "' ///
					10 `" "DC" "' ///
					11 `" "  " "FL" "' ///
					12 `" "GA" "' ///
					13 `" "  " "HI" "' ///
					14 `" "ID" "' ///
					15 `" "  " "IL" "' ///
					16 `" "IN" "' ///
					17 `" "  " "IA" "' ///
					18 `" "KS" "' ///
					19 `" "  " "KY" "' ///
					20 `" "LA" "' ///
					21 `" "  " "ME" "' ///
					22 `" "MD" "' ///
					23 `" "  " "MA" "' ///
					24 `" "MI" "' ///
					25 `" "  " "MN" "' ///
					26 `" "MS" "' ///
					27 `" "  " "MO" "' ///
					28 `" "MT" "' ///
					29 `" "  " "NE" "' ///
					30 `" "NV" "' ///
					31 `" "  " "NH" "' ///
					32 `" "NJ" "' ///
					33 `" "  " "NM" "' ///
					34 `" "NY" "' ///
					35 `" "  " "NC" "' ///
					36 `" "ND" "' ///
					37 `" "  " "OH" "' ///
					38 `" "OK" "' ///
					39 `" "  " "OR" "' ///
					40 `" "PA" "' ///
					41 `" "  " "PR" "' ///
					42 `" "RI" "' ///
					43 `" "  " "SC" "' ///
					44 `" "SD" "' ///
					45 `" "  " "TN" "' ///
					46 `" "TX" "' ///
					47 `" "  " "UT" "' ///
					48 `" "VT" "' ///
					49 `" "  " "VA" "' ///
					50 `" "WA" "' ///
					51 `" "  " "WV" "' ///
					52 `" "WI" "' ///
					53 `" "  " "WY" "' ///
			, labsize(vsmall) angle(0)) ///
			xline(1, lcolor(gs12)) ///
			xline(2, lcolor(gs12)) ///
			xline(3, lcolor(gs12)) ///
			xline(4, lcolor(gs12)) ///
			xline(5, lcolor(gs12)) ///
			xline(6, lcolor(gs12)) ///
			xline(7, lcolor(gs12)) ///
			xline(8, lcolor(gs12)) ///
			xline(9, lcolor(gs12)) ///
			xline(10, lcolor(gs12)) ///
			xline(11, lcolor(gs12)) ///
			xline(12, lcolor(gs12)) ///
			xline(13, lcolor(gs12)) ///
			xline(14, lcolor(gs12)) ///
			xline(15, lcolor(gs12)) ///
			xline(16, lcolor(gs12)) ///
			xline(17, lcolor(gs12)) ///
			xline(18, lcolor(gs12)) ///
			xline(19, lcolor(gs12)) ///
			xline(20, lcolor(gs12)) ///
			xline(21, lcolor(gs12)) ///
			xline(22, lcolor(gs12)) ///
			xline(23, lcolor(gs12)) ///
			xline(24, lcolor(gs12)) ///
			xline(25, lcolor(gs12)) ///
			xline(26, lcolor(gs12)) ///
			xline(27, lcolor(gs12)) ///
			xline(28, lcolor(gs12)) ///
			xline(29, lcolor(gs12)) ///
			xline(30, lcolor(gs12)) ///
			xline(31, lcolor(gs12)) ///
			xline(32, lcolor(gs12)) ///
			xline(33, lcolor(gs12)) ///
			xline(34, lcolor(gs12)) ///
			xline(35, lcolor(gs12)) ///
			xline(36, lcolor(gs12)) ///
			xline(37, lcolor(gs12)) ///
			xline(38, lcolor(gs12)) ///
			xline(39, lcolor(gs12)) ///
			xline(40, lcolor(gs12)) ///
			xline(41, lcolor(gs12)) ///
			xline(42, lcolor(gs12)) ///
			xline(43, lcolor(gs12)) ///
			xline(44, lcolor(gs12)) ///
			xline(45, lcolor(gs12)) ///
			xline(46, lcolor(gs12)) ///
			xline(47, lcolor(gs12)) ///
			xline(48, lcolor(gs12)) ///
			xline(49, lcolor(gs12)) ///
			xline(50, lcolor(gs12)) ///
			xline(51, lcolor(gs12)) ///
			xline(52, lcolor(gs12)) ///
			xline(53, lcolor(gs12)) ///
			xtitle("") ///
			ylabel(0 "0%" 20 "20%"  40 "40%" 60 "60%" 80 "80%" 100 "100%", angle(0)) ///
			ytitle("" " ", size(small)) ///
			title("Share of students enrolled in AP courses" "who took at least one AP exam, by Race or Ethnicity", position(11) justification(left) color("0 0 0") size(4)) ///
			legend(order(1 "Black" 2 "White" 3 "Asian" 4 "Hispanic") region(lwidth(none)) position(6) cols(4)) ///
			graphregion(color(white)) bgcolor(white) 
			
		graph export "${urbinst}\Graph 3_States.png", as(png) height(1000) replace
		
		
	restore
////////////////////////////////////////////////////////////////////////////////
	* CREATE GRAPH #4: RELATIVE COURSE-ENROLLMENT ACROSS GROUPS AT STATE-LEVEL (FOR APPENDIX) 	

	preserve
		sort state_name
		encode state_name, gen(state_code)
		generate state_abbrv = " US" if state_name=="50 states, District of Columbia, and Puerto Rico"
		replace state_abbrv = "AL" if state_name=="Alabama"
		replace state_abbrv = "AK" if state_name=="Alaska"
		replace state_abbrv = "AZ" if state_name=="Arizona"
		replace state_abbrv = "AR" if state_name=="Arkansas"
		replace state_abbrv = "CA" if state_name=="California"
		replace state_abbrv = "CO" if state_name=="Colorado"
		replace state_abbrv = "CT" if state_name=="Connecticut"
		replace state_abbrv = "DE" if state_name=="Delaware"
		replace state_abbrv = "DC" if state_name=="District of Columbia"
		replace state_abbrv = "FL" if state_name=="Florida"
		replace state_abbrv = "GA" if state_name=="Georgia"
		replace state_abbrv = "HI" if state_name=="Hawaii"
		replace state_abbrv = "ID" if state_name=="Idaho"
		replace state_abbrv = "IL" if state_name=="Illinois"
		replace state_abbrv = "IN" if state_name=="Indiana"
		replace state_abbrv = "IA" if state_name=="Iowa"
		replace state_abbrv = "KS" if state_name=="Kansas"
		replace state_abbrv = "KY" if state_name=="Kentucky"
		replace state_abbrv = "LA" if state_name=="Louisiana"
		replace state_abbrv = "ME" if state_name=="Maine"
		replace state_abbrv = "MD" if state_name=="Maryland"
		replace state_abbrv = "MA" if state_name=="Massachusetts"
		replace state_abbrv = "MI" if state_name=="Michigan"
		replace state_abbrv = "MN" if state_name=="Minnesota"
		replace state_abbrv = "MS" if state_name=="Mississippi"
		replace state_abbrv = "MO" if state_name=="Missouri"
		replace state_abbrv = "MT" if state_name=="Montana"
		replace state_abbrv = "NE" if state_name=="Nebraska"
		replace state_abbrv = "NV" if state_name=="Nevada"
		replace state_abbrv = "NH" if state_name=="New Hampshire"
		replace state_abbrv = "NJ" if state_name=="New Jersey"
		replace state_abbrv = "NM" if state_name=="New Mexico"
		replace state_abbrv = "NY" if state_name=="New York"
		replace state_abbrv = "NC" if state_name=="North Carolina"
		replace state_abbrv = "ND" if state_name=="North Dakota"
		replace state_abbrv = "OH" if state_name=="Ohio"
		replace state_abbrv = "OK" if state_name=="Oklahoma"
		replace state_abbrv = "OR" if state_name=="Oregon"
		replace state_abbrv = "PA" if state_name=="Pennsylvania"
		replace state_abbrv = "PR" if state_name=="Puerto Rico"
		replace state_abbrv = "RI" if state_name=="Rhode Island"
		replace state_abbrv = "SC" if state_name=="South Carolina"
		replace state_abbrv = "SD" if state_name=="South Dakota"
		replace state_abbrv = "TN" if state_name=="Tennessee"
		replace state_abbrv = "TX" if state_name=="Texas"
		replace state_abbrv = "UT" if state_name=="Utah"
		replace state_abbrv = "VT" if state_name=="Vermont"
		replace state_abbrv = "VA" if state_name=="Virginia"
		replace state_abbrv = "WA" if state_name=="Washington"
		replace state_abbrv = "WV" if state_name=="West Virginia"
		replace state_abbrv = "WI" if state_name=="Wisconsin"
		replace state_abbrv = "WY" if state_name=="Wyoming"
		graph bar APNO_perc_BLACK APNO_perc_WHITE APNO_perc_ASIAN APNO_perc_HISP APNO_perc_OTHER, over(state_abbrv, label(alt labsize(vsmall)))  stack ///
		bar(1, color("22 150 210"))   bar(2, color("85 183 72")) bar(3, color("92 88 89")) bar(4, color("253 191 17")) bar(5, color("0 0 0")) ///
			title("AP course enrollment by state and race" "") ///
			ylabel(0 "0%" 20 "20%"  40 "40%" 60 "60%" 80 "80%" 100 "100%", angle(0)) ///
			ytitle("", size(small)) ///
			legend(order(1 "Black" 2 "White" 3 "Asian" 4 "Hispanic" 5 "Other") region(lwidth(none)) position(6) cols(5)) ///
			graphregion(color(white)) bgcolor(white) 
			
	graph export  "${urbinst}\Graph 4_STATE-LEVEL_course enrollment.png", as(png) height(1000) replace
		
	restore
	
keep state_name APENR_num_* propYES_ENR* APYES* APNO*

rename APENR_num_* ap_enrolled_*
rename APYES_* takers_*
rename APNO_* nontakers_*
rename propYES_ENR_* propTakers_*
rename *SWDIDEA *wdisbility


export excel "${urbinst}\output_data.xlsx", firstrow(variables) replace